-- Generated by Oracle SQL Developer Data Modeler 22.2.0.165.1149
--   at:        2024-11-09 13:46:26 ICT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE admin (
    isaktif        CHAR(1) NOT NULL,
    created_at     TIMESTAMP NOT NULL,
    updated_at     TIMESTAMP NOT NULL,
    deleted_at     TIMESTAMP NOT NULL,
    users_id_users INTEGER NOT NULL
);

ALTER TABLE admin ADD CONSTRAINT admin_pk PRIMARY KEY ( users_id_users );

CREATE TABLE detail_transaksi (
    kuantitas              INTEGER NOT NULL,
    subtotalharga          VARCHAR2(255) NOT NULL,
    transaksi_id_transaksi INTEGER NOT NULL,
    menu_id_menu           INTEGER NOT NULL,
    created_at             TIMESTAMP NOT NULL,
    updated_at             TIMESTAMP NOT NULL,
    deleted_at             TIMESTAMP NOT NULL
);

ALTER TABLE detail_transaksi ADD CONSTRAINT detail_transaksi_pk PRIMARY KEY ( menu_id_menu,
                                                                              transaksi_id_transaksi );

CREATE TABLE list_kantin (
    id_kantin  INTEGER NOT NULL,
    namakantin VARCHAR2(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP NOT NULL
);

ALTER TABLE list_kantin ADD CONSTRAINT list_kantin_pk PRIMARY KEY ( id_kantin );

CREATE TABLE list_toko (
    istokobuka            CHAR(1) NOT NULL,
    list_kantin_id_kantin INTEGER NOT NULL,
    created_at            TIMESTAMP NOT NULL,
    updated_at            TIMESTAMP NOT NULL,
    deleted_at            TIMESTAMP NOT NULL,
    users_id_users        INTEGER NOT NULL
);

ALTER TABLE list_toko ADD CONSTRAINT list_toko_pk PRIMARY KEY ( users_id_users );

CREATE TABLE mahasiswa (
    nrp            VARCHAR2(255) NOT NULL,
    created_at     TIMESTAMP NOT NULL,
    updated_at     TIMESTAMP NOT NULL,
    deleted_at     TIMESTAMP NOT NULL,
    users_id_users INTEGER NOT NULL
);

ALTER TABLE mahasiswa ADD CONSTRAINT mahasiswa_pk PRIMARY KEY ( users_id_users );

ALTER TABLE mahasiswa ADD CONSTRAINT mahasiswa_nrp_un UNIQUE ( nrp );

CREATE TABLE menu (
    id_menu                  INTEGER NOT NULL,
    namamenu                 VARCHAR2(255) NOT NULL,
    harga                    VARCHAR2(255) NOT NULL,
    statustersedia           INTEGER NOT NULL,
    created_at               TIMESTAMP NOT NULL,
    updated_at               TIMESTAMP NOT NULL,
    deleted_at               TIMESTAMP NOT NULL,
    list_toko_users_id_users INTEGER NOT NULL
);

ALTER TABLE menu ADD CONSTRAINT menu_pk PRIMARY KEY ( id_menu );

CREATE TABLE rekam_bayar (
    waktubayar             TIMESTAMP NOT NULL,
    nominalbayar           VARCHAR2(255) NOT NULL,
    transaksi_id_transaksi INTEGER NOT NULL,
    created_at             TIMESTAMP NOT NULL,
    updated_at             TIMESTAMP NOT NULL,
    deleted_at             TIMESTAMP NOT NULL
);

ALTER TABLE rekam_bayar ADD CONSTRAINT rekam_bayar_pk PRIMARY KEY ( transaksi_id_transaksi );

CREATE TABLE status_pesanan (
    id_status_pesanan   INTEGER NOT NULL,
    nama_status_pesanan VARCHAR2(255) NOT NULL,
    created_at          TIMESTAMP NOT NULL,
    updated_at          TIMESTAMP NOT NULL,
    deleted_at          TIMESTAMP NOT NULL
);

ALTER TABLE status_pesanan ADD CONSTRAINT status_pesanan_pk PRIMARY KEY ( id_status_pesanan );

CREATE TABLE status_transaksi (
    id_status_pembayaran INTEGER NOT NULL,
    nama_status          VARCHAR2(255) NOT NULL,
    created_at           TIMESTAMP NOT NULL,
    updated_at           TIMESTAMP NOT NULL,
    deleted_at           TIMESTAMP NOT NULL,
    status_transaksi_id  NUMBER NOT NULL
);

ALTER TABLE status_transaksi ADD CONSTRAINT status_transaksi_pk PRIMARY KEY ( status_transaksi_id );

CREATE TABLE status_user (
    id_status   INTEGER NOT NULL,
    nama_status VARCHAR2(255) NOT NULL,
    created_at  TIMESTAMP NOT NULL,
    updated_at  TIMESTAMP NOT NULL,
    deleted_at  TIMESTAMP NOT NULL
);

ALTER TABLE status_user ADD CONSTRAINT status_user_pk PRIMARY KEY ( id_status );

CREATE TABLE transaksi (
    id_transaksi                         INTEGER NOT NULL,
    totalharga                           VARCHAR2(255) NOT NULL,
    created_at                           TIMESTAMP NOT NULL,
    updated_at                           TIMESTAMP NOT NULL,
    deleted_at                           TIMESTAMP NOT NULL,
    mahasiswa_id_users                   INTEGER NOT NULL, 
--  ERROR: Column name length exceeds maximum allowed length(30) 
    status_pesanan_id_status_pesanan     INTEGER NOT NULL, 
--  ERROR: Column name length exceeds maximum allowed length(30) 
    status_transaksi_status_transaksi_id NUMBER NOT NULL
);

ALTER TABLE transaksi ADD CONSTRAINT transaksi_pk PRIMARY KEY ( id_transaksi );

CREATE TABLE users (
    id_users              INTEGER NOT NULL,
    nama                  VARCHAR2(255) NOT NULL,
    email                 VARCHAR2(255) NOT NULL,
    password              VARCHAR2(255) NOT NULL,
    picture               VARCHAR2(255) NOT NULL,
    created_at            TIMESTAMP NOT NULL,
    updated_at            TIMESTAMP NOT NULL,
    deleted_at            TIMESTAMP NOT NULL,
    status_user_id_status INTEGER NOT NULL
);

ALTER TABLE users ADD CONSTRAINT users_pk PRIMARY KEY ( id_users );

ALTER TABLE admin
    ADD CONSTRAINT admin_users_fk FOREIGN KEY ( users_id_users )
        REFERENCES users ( id_users );

ALTER TABLE detail_transaksi
    ADD CONSTRAINT detail_transaksi_menu_fk FOREIGN KEY ( menu_id_menu )
        REFERENCES menu ( id_menu );

ALTER TABLE detail_transaksi
    ADD CONSTRAINT detail_transaksi_transaksi_fk FOREIGN KEY ( transaksi_id_transaksi )
        REFERENCES transaksi ( id_transaksi );

ALTER TABLE list_toko
    ADD CONSTRAINT list_toko_list_kantin_fk FOREIGN KEY ( list_kantin_id_kantin )
        REFERENCES list_kantin ( id_kantin );

ALTER TABLE list_toko
    ADD CONSTRAINT list_toko_users_fk FOREIGN KEY ( users_id_users )
        REFERENCES users ( id_users );

ALTER TABLE mahasiswa
    ADD CONSTRAINT mahasiswa_users_fk FOREIGN KEY ( users_id_users )
        REFERENCES users ( id_users );

ALTER TABLE menu
    ADD CONSTRAINT menu_list_toko_fk FOREIGN KEY ( list_toko_users_id_users )
        REFERENCES list_toko ( users_id_users );

ALTER TABLE rekam_bayar
    ADD CONSTRAINT rekam_bayar_transaksi_fk FOREIGN KEY ( transaksi_id_transaksi )
        REFERENCES transaksi ( id_transaksi );

ALTER TABLE transaksi
    ADD CONSTRAINT transaksi_mahasiswa_fk FOREIGN KEY ( mahasiswa_id_users )
        REFERENCES mahasiswa ( users_id_users );

ALTER TABLE transaksi
    ADD CONSTRAINT transaksi_status_pesanan_fk FOREIGN KEY ( status_pesanan_id_status_pesanan )
        REFERENCES status_pesanan ( id_status_pesanan );

ALTER TABLE transaksi
    ADD CONSTRAINT transaksi_status_transaksi_fk FOREIGN KEY ( status_transaksi_status_transaksi_id )
        REFERENCES status_transaksi ( status_transaksi_id );

ALTER TABLE users
    ADD CONSTRAINT users_status_user_fk FOREIGN KEY ( status_user_id_status )
        REFERENCES status_user ( id_status );

CREATE SEQUENCE status_transaksi_status_transa START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER status_transaksi_status_transa BEFORE
    INSERT ON status_transaksi
    FOR EACH ROW
    WHEN ( new.status_transaksi_id IS NULL )
BEGIN
    :new.status_transaksi_id := status_transaksi_status_transa.nextval;
END;
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            12
-- CREATE INDEX                             0
-- ALTER TABLE                             25
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           1
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          1
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   2
-- WARNINGS                                 0
